#!/bin/bash

echo "🔐 Configuration des credentials AWS"
echo "====================================="
echo ""
echo "Vous devez configurer vos credentials AWS avant le déploiement."
echo ""
echo "Option 1: AWS CLI Configure (Recommandé)"
echo "----------------------------------------"
echo "aws configure"
echo ""
echo "Vous devrez fournir:"
echo "  - AWS Access Key ID"
echo "  - AWS Secret Access Key"
echo "  - Default region (ex: us-east-1)"
echo "  - Default output format (json)"
echo ""
echo "Option 2: Variables d'environnement"
echo "-----------------------------------"
echo "export AWS_ACCESS_KEY_ID=\"votre_access_key\""
echo "export AWS_SECRET_ACCESS_KEY=\"votre_secret_key\""
echo "export AWS_DEFAULT_REGION=\"us-east-1\""
echo ""
echo "Option 3: Fichier credentials manuel"
echo "------------------------------------"
echo "Créez le fichier ~/.aws/credentials avec:"
echo ""
echo "[default]"
echo "aws_access_key_id = VOTRE_ACCESS_KEY"
echo "aws_secret_access_key = VOTRE_SECRET_KEY"
echo ""
echo "Et ~/.aws/config avec:"
echo ""
echo "[default]"
echo "region = us-east-1"
echo "output = json"
echo ""
echo "📝 Pour obtenir vos credentials AWS:"
echo "1. Connectez-vous à la console AWS"
echo "2. Allez dans IAM > Users > Votre utilisateur"
echo "3. Onglet 'Security credentials'"
echo "4. Créez une 'Access key' si nécessaire"
echo ""
echo "Une fois configuré, relancez:"
echo "./deploy.sh"
