#!/bin/bash

echo "🔐 AWS Credentials Configuration"
echo "============================="
echo ""
echo "You must configure your AWS credentials before deployment."
echo ""
echo "Option 1: AWS CLI Configure (Recommended)"
echo "----------------------------------------"
echo "aws configure"
echo ""
echo "You will need:"
echo "  - AWS Access Key ID"
echo "  - AWS Secret Access Key"
echo "  - Default region (e.g., us-east-1)"
echo "  - Default output format (json)"
echo ""
echo "Option 2: Environment Variables"
echo "-----------------------------------"
echo "export AWS_ACCESS_KEY_ID=\"your_access_key\""
echo "export AWS_SECRET_ACCESS_KEY=\"your_secret_key\""
echo "export AWS_DEFAULT_REGION=\"us-east-1\""
echo ""
echo "Option 3: Manual credentials file"
echo "------------------------------------"
echo "Create file ~/.aws/credentials with:"
echo ""
echo "[default]"
echo "aws_access_key_id = YOUR_ACCESS_KEY"
echo "aws_secret_access_key = YOUR_SECRET_KEY"
echo ""
echo "And ~/.aws/config with:"
echo ""
echo "[default]"
echo "region = us-east-1"
echo "output = json"
echo ""
echo "📝 To get your AWS credentials:"
echo "1. Log in to AWS Console"
echo "2. Go to IAM > Users > Your user"
echo "3. Tab 'Security credentials'"
echo "4. Create an 'Access key' if needed"
echo ""
echo "Once configured, run:"
echo "./deploy.sh"
